package com.vocis.intelligence.context

enum class ContextType {
    UNKNOWN,
    SUSPICIOUS_CALL_SEQUENCE,
    SOCIAL_ENGINEERING,
    FINANCIAL_FRAUD,
    OTP_THEFT,
    ACCOUNT_TAKEOVER,
    KYC_SCAM,
    BANKING_SOCIAL_ENGINEERING,
    TELECOM_IMPERSONATION,
    UTILITY_SCAM,
    PARCEL_SCAM,
    CHALLAN_SCAM,
    REMOTE_ACCESS_SCAM,
    GOVERNMENT_IMPERSONATION,
    REWARD_SCAM
}
