package com.vocis.intelligence.context

enum class InferredIntent {
    UNKNOWN,
    POSSIBLE_SOCIAL_ENGINEERING,
    POSSIBLE_FINANCIAL_FRAUD,
    POSSIBLE_OTP_THEFT,
    POSSIBLE_ACCOUNT_TAKEOVER,
    POSSIBLE_KYC_SCAM,
    POSSIBLE_REMOTE_ACCESS_SCAM,
    POSSIBLE_TELECOM_IMPERSONATION,
    POSSIBLE_UTILITY_SCAM,
    POSSIBLE_PARCEL_SCAM,
    POSSIBLE_GOVERNMENT_IMPERSONATION,
    POSSIBLE_REWARD_SCAM
}
